/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// AccountInvite An invitation for a user to join a Pureport account.
type AccountInvite struct {
	Account Link `json:"account"`
	// The email address of the user being invited to the Pureport account.
	Email   string `json:"email"`
	Expired bool   `json:"expired,omitempty"`
	// The URI of the Pureport asset.
	Href string `json:"href,omitempty"`
	// The id is a unique identifier representing the invite.
	Id        string    `json:"id,omitempty"`
	InvitedAt time.Time `json:"invitedAt,omitempty"`
	InvitedBy Link      `json:"invitedBy,omitempty"`
	// The Pureport roles the invited user will have permissions for on the account.
	Roles []Link `json:"roles"`
}
