/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// VpnAuthConfig VPN authentication configuration.
type VpnAuthConfig struct {
	Type IpSecAuthenticationType `json:"type,omitempty"`
}
