/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev1IkeIntegrityAlgorithm The integrity algorithm.
type Ikev1IkeIntegrityAlgorithm string

// List of IKEV1IKEIntegrityAlgorithm
const (
	MD5_HMAC    Ikev1IkeIntegrityAlgorithm = "MD5_HMAC"
	SHA1_HMAC   Ikev1IkeIntegrityAlgorithm = "SHA1_HMAC"
	SHA256_HMAC Ikev1IkeIntegrityAlgorithm = "SHA256_HMAC"
	SHA384_HMAC Ikev1IkeIntegrityAlgorithm = "SHA384_HMAC"
	SHA512_HMAC Ikev1IkeIntegrityAlgorithm = "SHA512_HMAC"
)
