/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingInterval The interval on which recurring charges will be charged.
type BillingInterval string

// List of BillingInterval
const (
	ONCE  BillingInterval = "ONCE"
	DAY   BillingInterval = "DAY"
	WEEK  BillingInterval = "WEEK"
	MONTH BillingInterval = "MONTH"
	YEAR  BillingInterval = "YEAR"
)
