/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AuditEntryRequest The request that triggered this entry.
type AuditEntryRequest struct {
	// The body of the request.
	Body string `json:"body,omitempty"`
	// The HTTP method of the request.
	Method string `json:"method,omitempty"`
	// The query parameters passed with the request.
	QueryParameters map[string][]string `json:"queryParameters,omitempty"`
	// The url of the request.
	Url string `json:"url,omitempty"`
}
