/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SupportedConnectionGroup A named grouping of Supported Connections
type SupportedConnectionGroup struct {
	// The URI of the Pureport asset.
	Href string `json:"href,omitempty"`
	// The id is a unique identifier representing the supported connection group.
	Id string `json:"id,omitempty"`
	// The name of this group.
	Name string `json:"name"`
}
