/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// CustomerNetwork struct for CustomerNetwork
type CustomerNetwork struct {
	Address string `json:"address"`
	Name    string `json:"name,omitempty"`
}
