/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PodStatus The current status of the pod.
type PodStatus string

// List of PodStatus
const (
	AVAILABLE   PodStatus = "AVAILABLE"
	UNAVAILABLE PodStatus = "UNAVAILABLE"
)
