/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// StandardGateway struct for StandardGateway
type StandardGateway struct {
	AvailabilityDomain string     `json:"availabilityDomain,omitempty"`
	BgpConfig          *BgpConfig `json:"bgpConfig,omitempty"`
	Description        string     `json:"description,omitempty"`
	ErrorCode          string     `json:"errorCode,omitempty"`
	ErrorMessage       string     `json:"errorMessage,omitempty"`
	Id                 string     `json:"id,omitempty"`
	LinkState          string     `json:"linkState,omitempty"`
	Name               string     `json:"name,omitempty"`
	RemoteId           string     `json:"remoteId,omitempty"`
	State              string     `json:"state,omitempty"`
	Type               string     `json:"type,omitempty"`
	Vlan               int32      `json:"vlan,omitempty"`
}
