/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// GatewayState The current state of the gateway.
type GatewayState string

// List of GatewayState
const (
	GATEWAY_STATE__WAITING_TO_PROVISION GatewayState = "WAITING_TO_PROVISION"
	GATEWAY_STATE__PROVISIONING         GatewayState = "PROVISIONING"
	GATEWAY_STATE__FAILED_TO_PROVISION  GatewayState = "FAILED_TO_PROVISION"
	GATEWAY_STATE__ACTIVE               GatewayState = "ACTIVE"
	GATEWAY_STATE__DOWN                 GatewayState = "DOWN"
	GATEWAY_STATE__UPDATING             GatewayState = "UPDATING"
	GATEWAY_STATE__FAILED_TO_UPDATE     GatewayState = "FAILED_TO_UPDATE"
	GATEWAY_STATE__DELETING             GatewayState = "DELETING"
	GATEWAY_STATE__FAILED_TO_DELETE     GatewayState = "FAILED_TO_DELETE"
	GATEWAY_STATE__DELETED              GatewayState = "DELETED"
)
