/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ResourceType the model 'ResourceType'
type ResourceType string

// List of ResourceType
const (
	MEMBER              ResourceType = "MEMBER"
	ROLE                ResourceType = "ROLE"
	CONNECTION          ResourceType = "CONNECTION"
	NETWORK             ResourceType = "NETWORK"
	ACCOUNT             ResourceType = "ACCOUNT"
	CLOUD_SERVICE_ROUTE ResourceType = "CLOUD_SERVICE_ROUTE"
)
