/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// NotificationImpactedService The list of Pureport services to be affected.
type NotificationImpactedService string

// List of NotificationImpactedService
const (
	PUREPORT_CONSOLE        NotificationImpactedService = "PUREPORT_CONSOLE"
	PUREPORT_API            NotificationImpactedService = "PUREPORT_API"
	PUREPORT_CONNECTIONS    NotificationImpactedService = "PUREPORT_CONNECTIONS"
	THIRD_PARTY_API         NotificationImpactedService = "THIRD_PARTY_API"
	THIRD_PARTY_CONNECTIONS NotificationImpactedService = "THIRD_PARTY_CONNECTIONS"
)
