/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Account struct for Account
type Account struct {
	Demo                      bool              `json:"demo,omitempty"`
	Description               string            `json:"description,omitempty"`
	HasChildren               bool              `json:"hasChildren,omitempty"`
	Href                      string            `json:"href,omitempty"`
	Id                        string            `json:"id,omitempty"`
	Name                      string            `json:"name"`
	Parent                    Link              `json:"parent,omitempty"`
	PricingHidden             bool              `json:"pricingHidden,omitempty"`
	ShowChildAccountPricing   bool              `json:"showChildAccountPricing,omitempty"`
	SupportedConnectionGroups []Link            `json:"supportedConnectionGroups,omitempty"`
	Tags                      map[string]string `json:"tags,omitempty"`
	TechnicalContactEmails    []string          `json:"technicalContactEmails,omitempty"`
	Verified                  bool              `json:"verified,omitempty"`
}
