/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// FacilityState The current state of the facility.
type FacilityState string

// List of FacilityState
const (
	ACTIVE      FacilityState = "ACTIVE"
	UNAVAILABLE FacilityState = "UNAVAILABLE"
	DELETED     FacilityState = "DELETED"
)
