/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Option struct for Option
type Option struct {
	Aead        bool   `json:"aead,omitempty"`
	Default     bool   `json:"default,omitempty"`
	Description string `json:"description,omitempty"`
	Unsafe      bool   `json:"unsafe,omitempty"`
	Value       string `json:"value,omitempty"`
}
