/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// CloudProvider The provider of the cloud service.
type CloudProvider string

// List of CloudProvider
const (
	CLOUD_PROVIDER__AWS           CloudProvider = "AWS"
	CLOUD_PROVIDER__AZURE         CloudProvider = "AZURE"
	CLOUD_PROVIDER__GOOGLE_CLOUD  CloudProvider = "GOOGLE_CLOUD"
	CLOUD_PROVIDER__ORACLE        CloudProvider = "ORACLE"
	CLOUD_PROVIDER__PACKET_FABRIC CloudProvider = "PACKET_FABRIC"
)
