/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AccountDetailedInvoice Detailed breakdown of line items for an invoice.
type AccountDetailedInvoice struct {
	Account Link `json:"account,omitempty"`
	// The invoice id.
	InvoiceId string `json:"invoiceId,omitempty"`
	// The line items for this invoice.
	Items []DetailedInvoiceItem `json:"items,omitempty"`
}
