/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// GoogleCloudInterconnectConnectionAllOf struct for GoogleCloudInterconnectConnectionAllOf
type GoogleCloudInterconnectConnectionAllOf struct {
	// The Pairing Key for the primary gateway of the Google Cloud Interconnect.
	PrimaryPairingKey string `json:"primaryPairingKey,omitempty"`
	// The Pairing Key for the secondary gateway of the Google Cloud Interconnect.
	SecondaryPairingKey string `json:"secondaryPairingKey,omitempty"`
}
