/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PortSpeed The speed for this port in Mbps.
type PortSpeed int32

// List of PortSpeed
const (
	PORT_SPEED__1000  PortSpeed = 1000
	PORT_SPEED__10000 PortSpeed = 10000
	PORT_SPEED__40000 PortSpeed = 40000
)
