/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// GatewayType The type.
type GatewayType string

// List of GatewayType
const (
	GATEWAY_TYPE__STANDARD GatewayType = "STANDARD"
	GATEWAY_TYPE__VPN      GatewayType = "VPN"
)
