/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PortProvider The provider for this port.
type PortProvider string

// List of PortProvider
const (
	PUREPORT      PortProvider = "PUREPORT"
	PACKET_FABRIC PortProvider = "PACKET_FABRIC"
)
