/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// ProviderVlan A Virtual LAN
type ProviderVlan struct {
	// Whether the vlan has been allocated.
	Allocated         bool      `json:"allocated"`
	LastAllocatedAt   time.Time `json:"lastAllocatedAt,omitempty"`
	LastDeallocatedAt time.Time `json:"lastDeallocatedAt,omitempty"`
	// The speed of the vlan in Mbps.
	Speed int32 `json:"speed,omitempty"`
	// The vlan number.
	Vlan int32 `json:"vlan"`
}
