/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AvailabilityDomain The availability domain designated for this port.
type AvailabilityDomain string

// List of AvailabilityDomain
const (
	PRIMARY   AvailabilityDomain = "PRIMARY"
	SECONDARY AvailabilityDomain = "SECONDARY"
)
