/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// NetworkState The current state.
type NetworkState string

// List of NetworkState
const (
	PENDING                  NetworkState = "PENDING"
	PROVISIONING             NetworkState = "PROVISIONING"
	PENDING_CONTROLLERS      NetworkState = "PENDING_CONTROLLERS"
	DELETING_CONTROLLERS     NetworkState = "DELETING_CONTROLLERS"
	PROVISIONING_CONTROLLERS NetworkState = "PROVISIONING_CONTROLLERS"
	ACTIVE                   NetworkState = "ACTIVE"
	DELETING                 NetworkState = "DELETING"
	DELETED                  NetworkState = "DELETED"
	ERROR                    NetworkState = "ERROR"
)
