/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ConnectionType The connection type of this configuration.
type ConnectionType string

// List of ConnectionType
const (
	AWS_DIRECT_CONNECT        ConnectionType = "AWS_DIRECT_CONNECT"
	AZURE_EXPRESS_ROUTE       ConnectionType = "AZURE_EXPRESS_ROUTE"
	EQUINIX_CLOUD_EXCHANGE    ConnectionType = "EQUINIX_CLOUD_EXCHANGE"
	GOOGLE_CLOUD_INTERCONNECT ConnectionType = "GOOGLE_CLOUD_INTERCONNECT"
	ORACLE_FAST_CONNECT       ConnectionType = "ORACLE_FAST_CONNECT"
	SITE_IPSEC_VPN            ConnectionType = "SITE_IPSEC_VPN"
	PORT                      ConnectionType = "PORT"
	PACKET_FABRIC             ConnectionType = "PACKET_FABRIC"
	COMCAST                   ConnectionType = "COMCAST"
	COX_COMMUNICATIONS        ConnectionType = "COX_COMMUNICATIONS"
	ELEMENT_CRITICAL          ConnectionType = "ELEMENT_CRITICAL"
	PACKET                    ConnectionType = "PACKET"
	ZAYO                      ConnectionType = "ZAYO"
)
