/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AuditEntryResponse struct for AuditEntryResponse
type AuditEntryResponse struct {
	Body string `json:"body,omitempty"`
	// Execution time in milliseconds
	ExecutionTime    int64  `json:"executionTime,omitempty"`
	StatusCode       int32  `json:"statusCode,omitempty"`
	StatusCodeFamily string `json:"statusCodeFamily,omitempty"`
}
