/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingLongHaul The long haul configuration for this billing plan.
type BillingLongHaul string

// List of BillingLongHaul
const (
	NOT_APPLICABLE BillingLongHaul = "NOT_APPLICABLE"
	METRO          BillingLongHaul = "METRO"
	USAGE          BillingLongHaul = "USAGE"
	DEDICATED      BillingLongHaul = "DEDICATED"
)
