/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PskAuthConfigAllOf struct for PskAuthConfigAllOf
type PskAuthConfigAllOf struct {
	Key string `json:"key,omitempty"`
}
