/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// AccountConsent struct for AccountConsent
type AccountConsent struct {
	ConsentAt time.Time `json:"consentAt,omitempty"`
	Href      string    `json:"href,omitempty"`
	UserId    string    `json:"userId,omitempty"`
}
