/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ConnectionProvider The provider of connections using this link.
type ConnectionProvider string

// List of ConnectionProvider
const (
	AWS                    ConnectionProvider = "AWS"
	GOOGLE_CLOUD           ConnectionProvider = "GOOGLE_CLOUD"
	EQUINIX_CLOUD_EXCHANGE ConnectionProvider = "EQUINIX_CLOUD_EXCHANGE"
	PUREPORT               ConnectionProvider = "PUREPORT"
	PACKET_FABRIC          ConnectionProvider = "PACKET_FABRIC"
	COMCAST                ConnectionProvider = "COMCAST"
	COX_COMMUNICATIONS     ConnectionProvider = "COX_COMMUNICATIONS"
	ELEMENT_CRITICAL       ConnectionProvider = "ELEMENT_CRITICAL"
	PACKET                 ConnectionProvider = "PACKET"
	ZAYO                   ConnectionProvider = "ZAYO"
)
