/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// GenericConnection struct for GenericConnection
type GenericConnection struct {
	ActiveAt                 time.Time                `json:"activeAt,omitempty"`
	AdvertiseInternalRoutes  bool                     `json:"advertiseInternalRoutes,omitempty"`
	BillingPlan              BillingPlan              `json:"billingPlan,omitempty"`
	BillingProvider          string                   `json:"billingProvider,omitempty"`
	BillingTerm              string                   `json:"billingTerm"`
	CreatedAt                time.Time                `json:"createdAt,omitempty"`
	CustomerASN              int64                    `json:"customerASN,omitempty"`
	CustomerNetworks         []CustomerNetwork        `json:"customerNetworks,omitempty"`
	DeletedAt                time.Time                `json:"deletedAt,omitempty"`
	Description              string                   `json:"description,omitempty"`
	ErrorCode                string                   `json:"errorCode,omitempty"`
	ErrorMessage             string                   `json:"errorMessage,omitempty"`
	HighAvailability         bool                     `json:"highAvailability"`
	Href                     string                   `json:"href,omitempty"`
	Id                       string                   `json:"id,omitempty"`
	Location                 Link                     `json:"location"`
	Name                     string                   `json:"name"`
	Nat                      NatConfig                `json:"nat,omitempty"`
	Network                  Link                     `json:"network,omitempty"`
	PrimaryGateway           Gateway                  `json:"primaryGateway,omitempty"`
	SecondaryGateway         Gateway                  `json:"secondaryGateway,omitempty"`
	Speed                    int32                    `json:"speed"`
	State                    string                   `json:"state,omitempty"`
	Tags                     map[string]string        `json:"tags,omitempty"`
	Type                     string                   `json:"type"`
	BgpPasswordConfiguration BgpPasswordConfiguration `json:"bgpPasswordConfiguration,omitempty"`
	GatewayCidr              string                   `json:"gatewayCidr,omitempty"`
	Peering                  PeeringConfiguration     `json:"peering,omitempty"`
	PrimaryGatewayIP         string                   `json:"primaryGatewayIP,omitempty"`
	PrimaryVlan              int32                    `json:"primaryVlan,omitempty"`
	RoutingType              string                   `json:"routingType,omitempty"`
	SecondaryGatewayIP       string                   `json:"secondaryGatewayIP,omitempty"`
	SecondaryVlan            int32                    `json:"secondaryVlan,omitempty"`
	StaticRoutes             []StaticRouteDto         `json:"staticRoutes,omitempty"`
	VirtualGatewayIP         string                   `json:"virtualGatewayIP,omitempty"`
}
