/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// CustomerNetwork A mapping of a customer side IPAddress with a user friendly name.
type CustomerNetwork struct {
	Address string `json:"address"`
	// The user provided name for the customer network.
	Name string `json:"name,omitempty"`
}
