/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingPlan struct for BillingPlan
type BillingPlan struct {
	Amount          float32 `json:"amount,omitempty"`
	BillingInterval string  `json:"billingInterval"`
	BillingLongHaul string  `json:"billingLongHaul,omitempty"`
	Id              string  `json:"id,omitempty"`
	SetupAmount     float32 `json:"setupAmount,omitempty"`
	Term            string  `json:"term"`
}
