/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// IpSecAuthenticationType The authentication type.
type IpSecAuthenticationType string

// List of IPSecAuthenticationType
const (
	PSK IpSecAuthenticationType = "PSK"
)
