/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Notification struct for Notification
type Notification struct {
	AvailabilityDomain string    `json:"availabilityDomain,omitempty"`
	ConnectionTypes    []string  `json:"connectionTypes,omitempty"`
	CreatedAt          time.Time `json:"createdAt,omitempty"`
	Description        string    `json:"description,omitempty"`
	End                time.Time `json:"end"`
	Href               string    `json:"href,omitempty"`
	Id                 string    `json:"id,omitempty"`
	ImpactedServices   []string  `json:"impactedServices"`
	Locations          []Link    `json:"locations,omitempty"`
	Start              time.Time `json:"start"`
	State              string    `json:"state,omitempty"`
	Type               string    `json:"type"`
	UpdatedAt          time.Time `json:"updatedAt,omitempty"`
}
