/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// NotificationType The type.
type NotificationType string

// List of NotificationType
const (
	NOTIFICATION_TYPE__INCIDENT           NotificationType = "INCIDENT"
	NOTIFICATION_TYPE__MAINTENANCE_WINDOW NotificationType = "MAINTENANCE_WINDOW"
)
