/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingPlan struct for BillingPlan
type BillingPlan struct {
	Amount          float64 `json:"amount,omitempty"`
	BillingInterval string  `json:"billingInterval,omitempty"`
	Id              string  `json:"id,omitempty"`
	SetupAmount     int64   `json:"setupAmount,omitempty"`
	Term            string  `json:"term,omitempty"`
}
