/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AwsDirectConnectConnectionAllOf struct for AwsDirectConnectConnectionAllOf
type AwsDirectConnectConnectionAllOf struct {
	// The AWS Account ID, a 12-digit number that you use to construct Amazon Resource Names (ARNs).
	AwsAccountId string `json:"awsAccountId,omitempty"`
	// The AWS Region for the connection. This has been deprecated in favor of cloudRegion.
	AwsRegion                string                    `json:"awsRegion,omitempty"`
	BgpPasswordConfiguration *BgpPasswordConfiguration `json:"bgpPasswordConfiguration,omitempty"`
	CloudRegion              *Link                     `json:"cloudRegion,omitempty"`
	// The asset link for the clouds services associated with this connection.
	CloudServices []Link `json:"cloudServices,omitempty"`
	// The whitelisted cloud services CIDR blocks.
	CloudServicesPrefixWhitelist []string              `json:"cloudServicesPrefixWhitelist,omitempty"`
	Peering                      *PeeringConfiguration `json:"peering,omitempty"`
}
