/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// PublicPeeringPoolStats struct for PublicPeeringPoolStats
type PublicPeeringPoolStats struct {
	Time              time.Time `json:"time,omitempty"`
	TotalAllocatedIps int32     `json:"totalAllocatedIps,omitempty"`
	TotalBlocks       int32     `json:"totalBlocks,omitempty"`
	TotalDeletedIps   int32     `json:"totalDeletedIps,omitempty"`
	TotalFreeIps      int32     `json:"totalFreeIps,omitempty"`
	TotalIps          int32     `json:"totalIps,omitempty"`
	TotalSubnets      int32     `json:"totalSubnets,omitempty"`
}
