/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingProvider The provider used for billing this connection.
type BillingProvider string

// List of BillingProvider
const (
	STRIPE BillingProvider = "STRIPE"
)
