/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SortDirection the model 'SortDirection'
type SortDirection string

// List of SortDirection
const (
	SORT_DIRECTION__ASC  SortDirection = "ASC"
	SORT_DIRECTION__DESC SortDirection = "DESC"
)
