/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingCollectionMethod The collection method.
type BillingCollectionMethod string

// List of BillingCollectionMethod
const (
	BILLING_COLLECTION_METHOD__CREDIT_CARD BillingCollectionMethod = "CREDIT_CARD"
	BILLING_COLLECTION_METHOD__NET_30      BillingCollectionMethod = "NET_30"
)
