/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// StaticRoute The IKE Phase configuration.
type StaticRoute struct {
	Network string `json:"network"`
	NextHop string `json:"nextHop"`
}
