/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// LinkState The link state.
type LinkState string

// List of LinkState
const (
	LINK_STATE__UP      LinkState = "UP"
	LINK_STATE__DOWN    LinkState = "DOWN"
	LINK_STATE__PENDING LinkState = "PENDING"
)
