/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// StandardGateway Pureport network gateway.
type StandardGateway struct {
	AvailabilityDomain AvailabilityDomain `json:"availabilityDomain,omitempty"`
	BgpConfig          *BgpConfig         `json:"bgpConfig,omitempty"`
	Connection         *Link              `json:"connection,omitempty"`
	// The description.
	Description string    `json:"description,omitempty"`
	ErrorCode   ErrorCode `json:"errorCode,omitempty"`
	// The error message if the gateway is in an error state.
	ErrorMessage string `json:"errorMessage,omitempty"`
	// The URI of the Pureport asset.
	Href string `json:"href,omitempty"`
	// The id is a unique identifier representing the gateway.
	Id        string    `json:"id,omitempty"`
	LinkState LinkState `json:"linkState,omitempty"`
	// The name.
	Name                      string `json:"name,omitempty"`
	PureportInternalGatewayIP string `json:"pureportInternalGatewayIP,omitempty"`
	// The ID of any resources attached to the gateway.
	RemoteId string       `json:"remoteId,omitempty"`
	State    GatewayState `json:"state,omitempty"`
	Type     GatewayType  `json:"type,omitempty"`
	// The version of the gateway container.
	Version string `json:"version,omitempty"`
	// The vlan number.
	Vlan int32 `json:"vlan,omitempty"`
}
