/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// IkeVersion The IKE version.
type IkeVersion string

// List of IKEVersion
const (
	V1 IkeVersion = "V1"
	V2 IkeVersion = "V2"
)
