/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev1DiffieHellmanGroup The Diffie-Hellman Group.
type Ikev1DiffieHellmanGroup string

// List of IKEV1DiffieHellmanGroup
const (
	MODP_1024 Ikev1DiffieHellmanGroup = "MODP_1024"
	MODP_1536 Ikev1DiffieHellmanGroup = "MODP_1536"
	MODP_2048 Ikev1DiffieHellmanGroup = "MODP_2048"
	MODP_3072 Ikev1DiffieHellmanGroup = "MODP_3072"
	MODP_4096 Ikev1DiffieHellmanGroup = "MODP_4096"
	MODP_6144 Ikev1DiffieHellmanGroup = "MODP_6144"
	MODP_8192 Ikev1DiffieHellmanGroup = "MODP_8192"
	ECP_192   Ikev1DiffieHellmanGroup = "ECP_192"
	ECP_224   Ikev1DiffieHellmanGroup = "ECP_224"
	ECP_256   Ikev1DiffieHellmanGroup = "ECP_256"
	ECP_384   Ikev1DiffieHellmanGroup = "ECP_384"
	ECP_521   Ikev1DiffieHellmanGroup = "ECP_521"
)
