/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev2IkeEncryptionAlgorithm The encryption algorithm.
type Ikev2IkeEncryptionAlgorithm string

// List of IKEV2IKEEncryptionAlgorithm
const (
	NULL            Ikev2IkeEncryptionAlgorithm = "NULL"
	AES_128         Ikev2IkeEncryptionAlgorithm = "AES_128"
	AES_192         Ikev2IkeEncryptionAlgorithm = "AES_192"
	AES_256         Ikev2IkeEncryptionAlgorithm = "AES_256"
	AES_128_CTR     Ikev2IkeEncryptionAlgorithm = "AES_128_CTR"
	AES_192_CTR     Ikev2IkeEncryptionAlgorithm = "AES_192_CTR"
	AES_256_CTR     Ikev2IkeEncryptionAlgorithm = "AES_256_CTR"
	AES_128_GCM_64  Ikev2IkeEncryptionAlgorithm = "AES_128_GCM_64"
	AES_192_GCM_64  Ikev2IkeEncryptionAlgorithm = "AES_192_GCM_64"
	AES_256_GCM_64  Ikev2IkeEncryptionAlgorithm = "AES_256_GCM_64"
	AES_128_GCM_96  Ikev2IkeEncryptionAlgorithm = "AES_128_GCM_96"
	AES_192_GCM_96  Ikev2IkeEncryptionAlgorithm = "AES_192_GCM_96"
	AES_256_GCM_96  Ikev2IkeEncryptionAlgorithm = "AES_256_GCM_96"
	AES_128_GCM_128 Ikev2IkeEncryptionAlgorithm = "AES_128_GCM_128"
	AES_192_GCM_128 Ikev2IkeEncryptionAlgorithm = "AES_192_GCM_128"
	AES_256_GCM_128 Ikev2IkeEncryptionAlgorithm = "AES_256_GCM_128"
)
