/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ConnectivityByGateway struct for ConnectivityByGateway
type ConnectivityByGateway struct {
	Average            float64      `json:"average,omitempty"`
	DestinationAddress string       `json:"destinationAddress,omitempty"`
	Gateway            Link         `json:"gateway,omitempty"`
	LossRate           float64      `json:"lossRate,omitempty"`
	Max                float64      `json:"max,omitempty"`
	Min                float64      `json:"min,omitempty"`
	StandardDeviation  float64      `json:"standardDeviation,omitempty"`
	Time               InstantRange `json:"time,omitempty"`
}
