/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TaskType The type.
type TaskType string

// List of TaskType
const (
	TASK_TYPE__IPSEC_RESTART               TaskType = "IPSEC_RESTART"
	TASK_TYPE__PING                        TaskType = "PING"
	TASK_TYPE__CHANGE_CONNECTION_SPEED     TaskType = "CHANGE_CONNECTION_SPEED"
	TASK_TYPE__CREATE_OR_UPDATE_CONNECTION TaskType = "CREATE_OR_UPDATE_CONNECTION"
	TASK_TYPE__DELETE_CONNECTION           TaskType = "DELETE_CONNECTION"
	TASK_TYPE__STOP_GATEWAY                TaskType = "STOP_GATEWAY"
	TASK_TYPE__START_GATEWAY               TaskType = "START_GATEWAY"
	TASK_TYPE__DELETE_GATEWAY              TaskType = "DELETE_GATEWAY"
	TASK_TYPE__RESPAWN_GATEWAYS            TaskType = "RESPAWN_GATEWAYS"
	TASK_TYPE__RESPAWN_NETWORK             TaskType = "RESPAWN_NETWORK"
	TASK_TYPE__RESPAWN_WITH_CLOUD_SERVICES TaskType = "RESPAWN_WITH_CLOUD_SERVICES"
)
