/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AccountNotification A notification for a particular account.
type AccountNotification struct {
	// A list of asset links of connections this notification applies to.
	Connections  []Link       `json:"connections,omitempty"`
	Notification Notification `json:"notification,omitempty"`
}
