/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingLongHaul The long haul configuration for this billing plan.
type BillingLongHaul string

// List of BillingLongHaul
const (
	BILLING_LONG_HAUL__NOT_APPLICABLE BillingLongHaul = "NOT_APPLICABLE"
	BILLING_LONG_HAUL__METRO          BillingLongHaul = "METRO"
	BILLING_LONG_HAUL__USAGE          BillingLongHaul = "USAGE"
	BILLING_LONG_HAUL__DEDICATED      BillingLongHaul = "DEDICATED"
)
