/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AccountBilling struct for AccountBilling
type AccountBilling struct {
	Account          Link            `json:"account"`
	Address          PhysicalAddress `json:"address"`
	CollectionMethod string          `json:"collectionMethod"`
	Email            string          `json:"email"`
	Href             string          `json:"href,omitempty"`
	Name             string          `json:"name"`
	StripeExpiry     string          `json:"stripeExpiry,omitempty"`
	StripeLastFour   string          `json:"stripeLastFour,omitempty"`
	StripeToken      string          `json:"stripeToken,omitempty"`
}
