/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PeeringConfiguration struct for PeeringConfiguration
type PeeringConfiguration struct {
	PrimaryPureportBgpIP   string `json:"primaryPureportBgpIP,omitempty"`
	PrimaryRemoteBgpIP     string `json:"primaryRemoteBgpIP,omitempty"`
	SecondaryPureportBgpIP string `json:"secondaryPureportBgpIP,omitempty"`
	SecondaryRemoteBgpIP   string `json:"secondaryRemoteBgpIP,omitempty"`
	Type                   string `json:"type"`
}
