/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Location struct for Location
type Location struct {
	GeoCoordinates GeoCoordinates           `json:"geoCoordinates"`
	Href           string                   `json:"href,omitempty"`
	Id             string                   `json:"id"`
	LocationLinks  []LocationLinkConnection `json:"locationLinks,omitempty"`
	Name           string                   `json:"name"`
}
