/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AuditEntryRequest struct for AuditEntryRequest
type AuditEntryRequest struct {
	Body            string              `json:"body,omitempty"`
	Method          string              `json:"method,omitempty"`
	QueryParameters map[string][]string `json:"queryParameters,omitempty"`
	Url             string              `json:"url,omitempty"`
}
