/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev2EspEncryptionAlgorithm The encryption algorithm.
type Ikev2EspEncryptionAlgorithm string

// List of IKEV2ESPEncryptionAlgorithm
const (
	NULL            Ikev2EspEncryptionAlgorithm = "NULL"
	AES_128         Ikev2EspEncryptionAlgorithm = "AES_128"
	AES_192         Ikev2EspEncryptionAlgorithm = "AES_192"
	AES_256         Ikev2EspEncryptionAlgorithm = "AES_256"
	AES_128_CTR     Ikev2EspEncryptionAlgorithm = "AES_128_CTR"
	AES_192_CTR     Ikev2EspEncryptionAlgorithm = "AES_192_CTR"
	AES_256_CTR     Ikev2EspEncryptionAlgorithm = "AES_256_CTR"
	AES_128_GCM_64  Ikev2EspEncryptionAlgorithm = "AES_128_GCM_64"
	AES_192_GCM_64  Ikev2EspEncryptionAlgorithm = "AES_192_GCM_64"
	AES_256_GCM_64  Ikev2EspEncryptionAlgorithm = "AES_256_GCM_64"
	AES_128_GCM_96  Ikev2EspEncryptionAlgorithm = "AES_128_GCM_96"
	AES_192_GCM_96  Ikev2EspEncryptionAlgorithm = "AES_192_GCM_96"
	AES_256_GCM_96  Ikev2EspEncryptionAlgorithm = "AES_256_GCM_96"
	AES_128_GCM_128 Ikev2EspEncryptionAlgorithm = "AES_128_GCM_128"
	AES_192_GCM_128 Ikev2EspEncryptionAlgorithm = "AES_192_GCM_128"
	AES_256_GCM_128 Ikev2EspEncryptionAlgorithm = "AES_256_GCM_128"
	AES_128_GMAC    Ikev2EspEncryptionAlgorithm = "AES_128_GMAC"
	AES_192_GMAC    Ikev2EspEncryptionAlgorithm = "AES_192_GMAC"
	AES_256_GMAC    Ikev2EspEncryptionAlgorithm = "AES_256_GMAC"
)
