/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Link Information for the specified Pureport asset.
type Link struct {
	// The URI for the Pureport asset.
	Href string `json:"href"`
	// The id is a unique identifier representing the Pureport asset.
	Id string `json:"id,omitempty"`
	// The title for the Pureport asset.
	Title string `json:"title,omitempty"`
}
