/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ApiKey struct for ApiKey
type ApiKey struct {
	Account     Link   `json:"account,omitempty"`
	Description string `json:"description,omitempty"`
	Href        string `json:"href,omitempty"`
	Key         string `json:"key,omitempty"`
	Name        string `json:"name,omitempty"`
	Roles       []Link `json:"roles,omitempty"`
	Secret      string `json:"secret,omitempty"`
}
