/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// PortConnection struct for PortConnection
type PortConnection struct {
	ActiveAt                 time.Time                `json:"activeAt,omitempty"`
	AdvertiseInternalRoutes  bool                     `json:"advertiseInternalRoutes,omitempty"`
	BillingPlan              BillingPlan              `json:"billingPlan,omitempty"`
	BillingProvider          string                   `json:"billingProvider,omitempty"`
	BillingTerm              string                   `json:"billingTerm"`
	CreatedAt                time.Time                `json:"createdAt,omitempty"`
	CustomerASN              int64                    `json:"customerASN,omitempty"`
	CustomerNetworks         []CustomerNetwork        `json:"customerNetworks,omitempty"`
	DeletedAt                time.Time                `json:"deletedAt,omitempty"`
	Description              string                   `json:"description,omitempty"`
	ErrorCode                string                   `json:"errorCode,omitempty"`
	ErrorMessage             string                   `json:"errorMessage,omitempty"`
	HighAvailability         bool                     `json:"highAvailability"`
	Href                     string                   `json:"href,omitempty"`
	Id                       string                   `json:"id,omitempty"`
	Location                 Link                     `json:"location"`
	Name                     string                   `json:"name"`
	Nat                      NatConfig                `json:"nat,omitempty"`
	Network                  Link                     `json:"network,omitempty"`
	PrimaryGateway           Gateway                  `json:"primaryGateway,omitempty"`
	SecondaryGateway         Gateway                  `json:"secondaryGateway,omitempty"`
	Speed                    int32                    `json:"speed"`
	State                    string                   `json:"state,omitempty"`
	Tags                     map[string]string        `json:"tags,omitempty"`
	Type                     string                   `json:"type"`
	BgpPasswordConfiguration BgpPasswordConfiguration `json:"bgpPasswordConfiguration,omitempty"`
	BillingLongHaul          string                   `json:"billingLongHaul,omitempty"`
	GatewayCidr              string                   `json:"gatewayCidr,omitempty"`
	PrimaryCustomerVlan      int32                    `json:"primaryCustomerVlan"`
	PrimaryGatewayIP         string                   `json:"primaryGatewayIP,omitempty"`
	PrimaryPort              Link                     `json:"primaryPort"`
	RoutingType              string                   `json:"routingType,omitempty"`
	SecondaryCustomerVlan    int32                    `json:"secondaryCustomerVlan,omitempty"`
	SecondaryGatewayIP       string                   `json:"secondaryGatewayIP,omitempty"`
	SecondaryPort            Link                     `json:"secondaryPort,omitempty"`
	StaticRoutes             []StaticRouteDto         `json:"staticRoutes,omitempty"`
	VirtualGatewayIP         string                   `json:"virtualGatewayIP,omitempty"`
}
