/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// GatewayState The current state of the gateway.
type GatewayState string

// List of GatewayState
const (
	WAITING_TO_PROVISION GatewayState = "WAITING_TO_PROVISION"
	PROVISIONING         GatewayState = "PROVISIONING"
	FAILED_TO_PROVISION  GatewayState = "FAILED_TO_PROVISION"
	ACTIVE               GatewayState = "ACTIVE"
	DOWN                 GatewayState = "DOWN"
	UPDATING             GatewayState = "UPDATING"
	FAILED_TO_UPDATE     GatewayState = "FAILED_TO_UPDATE"
	DELETING             GatewayState = "DELETING"
	FAILED_TO_DELETE     GatewayState = "FAILED_TO_DELETE"
	DELETED              GatewayState = "DELETED"
)
