/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// LoginRequest struct for LoginRequest
type LoginRequest struct {
	Key    string `json:"key"`
	Secret string `json:"secret"`
}
