/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AuditEntrySource The source of the request that triggered this entry.
type AuditEntrySource string

// List of AuditEntrySource
const (
	AUDIT_ENTRY_SOURCE__API     AuditEntrySource = "API"
	AUDIT_ENTRY_SOURCE__CONSOLE AuditEntrySource = "CONSOLE"
	AUDIT_ENTRY_SOURCE__SYSTEM  AuditEntrySource = "SYSTEM"
)
