/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ProviderLink struct for ProviderLink
type ProviderLink struct {
	AvailabilityDomain       string   `json:"availabilityDomain"`
	Href                     string   `json:"href,omitempty"`
	Id                       string   `json:"id"`
	MaxAvailableBandwidth    int32    `json:"maxAvailableBandwidth"`
	Pod                      Link     `json:"pod"`
	Provider                 string   `json:"provider"`
	ProviderId               string   `json:"providerId"`
	ProviderRegion           string   `json:"providerRegion,omitempty"`
	Speed                    int32    `json:"speed"`
	Status                   string   `json:"status"`
	SupportedConnectionTypes []string `json:"supportedConnectionTypes"`
	Vlans                    string   `json:"vlans"`
}
