/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Link struct for Link
type Link struct {
	Href  string `json:"href"`
	Id    string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
}
