/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev2EspConfig IKE Version 2 Encapsulating Security Payload configuration.
type Ikev2EspConfig struct {
	// The Diffie-Hellman Group.
	DhGroup string `json:"dhGroup"`
	// The encryption algorithm.
	Encryption string `json:"encryption"`
	// The integrity algorithm.
	Integrity string `json:"integrity,omitempty"`
	// The lifetime of the Security Association (SA).
	Lifetime int32 `json:"lifetime,omitempty"`
}
