/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ProviderLinkStatus The current status of this link.
type ProviderLinkStatus string

// List of ProviderLinkStatus
const (
	PROVIDER_LINK_STATUS__AVAILABLE   ProviderLinkStatus = "AVAILABLE"
	PROVIDER_LINK_STATUS__UNAVAILABLE ProviderLinkStatus = "UNAVAILABLE"
)
