/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PeeringType The peering type of this configuration.
type PeeringType string

// List of PeeringType
const (
	PEERING_TYPE__PUBLIC  PeeringType = "PUBLIC"
	PEERING_TYPE__PRIVATE PeeringType = "PRIVATE"
	PEERING_TYPE__TRANSIT PeeringType = "TRANSIT"
)
