/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AccountNotificationStatus the model 'AccountNotificationStatus'
type AccountNotificationStatus string

// List of AccountNotificationStatus
const (
	READ   AccountNotificationStatus = "READ"
	UNREAD AccountNotificationStatus = "UNREAD"
)
