/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AzureExpressRouteConnectionAllOf struct for AzureExpressRouteConnectionAllOf
type AzureExpressRouteConnectionAllOf struct {
	Peering    PeeringConfiguration `json:"peering,omitempty"`
	ServiceKey string               `json:"serviceKey,omitempty"`
}
