/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ConnectionState The current state of the connection.
type ConnectionState string

// List of ConnectionState
const (
	CONNECTION_STATE__INITIALIZING         ConnectionState = "INITIALIZING"
	CONNECTION_STATE__WAITING_TO_PROVISION ConnectionState = "WAITING_TO_PROVISION"
	CONNECTION_STATE__PENDING_APPROVAL     ConnectionState = "PENDING_APPROVAL"
	CONNECTION_STATE__APPROVED             ConnectionState = "APPROVED"
	CONNECTION_STATE__PROVISIONING         ConnectionState = "PROVISIONING"
	CONNECTION_STATE__FAILED_TO_PROVISION  ConnectionState = "FAILED_TO_PROVISION"
	CONNECTION_STATE__ACTIVE               ConnectionState = "ACTIVE"
	CONNECTION_STATE__DOWN                 ConnectionState = "DOWN"
	CONNECTION_STATE__UPDATING             ConnectionState = "UPDATING"
	CONNECTION_STATE__FAILED_TO_UPDATE     ConnectionState = "FAILED_TO_UPDATE"
	CONNECTION_STATE__DELETING             ConnectionState = "DELETING"
	CONNECTION_STATE__FAILED_TO_DELETE     ConnectionState = "FAILED_TO_DELETE"
	CONNECTION_STATE__DELETED              ConnectionState = "DELETED"
)
