/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Facility A data center facility.
type Facility struct {
	Address PhysicalAddress `json:"address"`
	// A mapping of alternate identifiers associated with the facility.
	AltIds map[string]string `json:"altIds,omitempty"`
	// The URI of the Pureport asset.
	Href string `json:"href,omitempty"`
	// The id is a unique identifier representing the facility.
	Id string `json:"id"`
	// The name of the facility.
	Name string `json:"name"`
	// The current state of the facility.
	State string `json:"state,omitempty"`
	// The vendor of the facility.
	Vendor string `json:"vendor"`
}
