/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AccessSwitchStatus the model 'AccessSwitchStatus'
type AccessSwitchStatus string

// List of AccessSwitchStatus
const (
	ACCESS_SWITCH_STATUS__AVAILABLE   AccessSwitchStatus = "AVAILABLE"
	ACCESS_SWITCH_STATUS__UNAVAILABLE AccessSwitchStatus = "UNAVAILABLE"
)
