/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SupportedConnection Connection configuration currently supported by Pureport
type SupportedConnection struct {
	// Billing plans available for this configuration.
	BillingPlans []BillingPlan `json:"billingPlans,omitempty"`
	// Association between billing providers and the product to bill under for this configuration.
	BillingProductIds map[string]string `json:"billingProductIds"`
	// The groups this connection configuration belongs to.
	Groups []Link `json:"groups,omitempty"`
	// Whether connections using this configuration have redundant gateways for failover.
	HighAvailability bool `json:"highAvailability"`
	// The URI of the Pureport asset.
	Href string `json:"href,omitempty"`
	// The id is a unique identifier representing the supported connection configuration.
	Id       string `json:"id,omitempty"`
	Location Link   `json:"location"`
	// The peering type of this configuration.
	PeeringType string `json:"peeringType"`
	// Whether this configuration is currently available or requires additional steps from Pureport.
	Pending bool `json:"pending"`
	// The cloud regions this configuration allows.
	ReachableCloudRegions []Link `json:"reachableCloudRegions,omitempty"`
	// Whether connections using this configuration require approval from Pureport to provision.
	RequiresApproval bool `json:"requiresApproval"`
	// The connection speed in Mbps of this configuration.
	Speed int32 `json:"speed"`
	// The connection type of this configuration.
	Type string `json:"type"`
}
