/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// UsageByConnectionAndTimeOptions struct for UsageByConnectionAndTimeOptions
type UsageByConnectionAndTimeOptions struct {
	ConnectionIds []string    `json:"connectionIds"`
	Date          DateFilter  `json:"date,omitempty"`
	TimeUnit      TimeUnit    `json:"timeUnit,omitempty"`
	TrafficType   TrafficType `json:"trafficType,omitempty"`
}
