/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// AccountConsent Status of an account of consent to the Terms of Service and Acceptable Use Policy
type AccountConsent struct {
	ConsentAt time.Time `json:"consentAt,omitempty"`
	Href      string    `json:"href,omitempty"`
	// The id of the user who has read and accepted Pureport's legal documentation.
	UserId string `json:"userId,omitempty"`
}
