/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// NatConfig struct for NatConfig
type NatConfig struct {
	Blocks   []string     `json:"blocks,omitempty"`
	Enabled  bool         `json:"enabled,omitempty"`
	Mappings []NatMapping `json:"mappings,omitempty"`
	PnatCidr string       `json:"pnatCidr,omitempty"`
}
