/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Ikev1IkeEncryptionAlgorithm The encryption algorithm.
type Ikev1IkeEncryptionAlgorithm string

// List of IKEV1IKEEncryptionAlgorithm
const (
	IKEV1_IKE__128 Ikev1IkeEncryptionAlgorithm = "AES_128"
	IKEV1_IKE__192 Ikev1IkeEncryptionAlgorithm = "AES_192"
	IKEV1_IKE__256 Ikev1IkeEncryptionAlgorithm = "AES_256"
)
