/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TimeUnit the model 'TimeUnit'
type TimeUnit string

// List of TimeUnit
const (
	TIME_UNIT__HOURS TimeUnit = "HOURS"
	TIME_UNIT__DAYS  TimeUnit = "DAYS"
)
