/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ResourceType the model 'ResourceType'
type ResourceType string

// List of ResourceType
const (
	RESOURCE_TYPE__MEMBER              ResourceType = "MEMBER"
	RESOURCE_TYPE__ROLE                ResourceType = "ROLE"
	RESOURCE_TYPE__CONNECTION          ResourceType = "CONNECTION"
	RESOURCE_TYPE__NETWORK             ResourceType = "NETWORK"
	RESOURCE_TYPE__ACCOUNT             ResourceType = "ACCOUNT"
	RESOURCE_TYPE__CLOUD_SERVICE_ROUTE ResourceType = "CLOUD_SERVICE_ROUTE"
)
