/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PacketFabricCustomer The Packet Fabric customer information.
type PacketFabricCustomer struct {
	Id   string `json:"id"`
	Name string `json:"name,omitempty"`
}
