/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SupportedPort Port configuration currently supported by Pureport
type SupportedPort struct {
	// The availability domains supported by this configuration.
	AvailabilityDomains []string `json:"availabilityDomains,omitempty"`
	// The billing plans supported by this configuration.
	BillingPlans []BillingPlan `json:"billingPlans,omitempty"`
	Facility     Link          `json:"facility,omitempty"`
	// The media types supported by this configuration.
	MediaTypes []string `json:"mediaTypes,omitempty"`
	// The provider for this configuration.
	Provider string `json:"provider,omitempty"`
	// The speed of this configuration in Mbps.
	Speed int32 `json:"speed,omitempty"`
}
