/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Contact: support@pureport.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TaskState the model 'TaskState'
type TaskState string

// List of TaskState
const (
	CREATED   TaskState = "CREATED"
	RUNNING   TaskState = "RUNNING"
	COMPLETED TaskState = "COMPLETED"
	FAILED    TaskState = "FAILED"
	DELETED   TaskState = "DELETED"
	AGGREGATE TaskState = "AGGREGATE"
)
