/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PublicPeeringBlock struct {
	CidrBlock string `json:"cidrBlock"`
	CreatedAt int64  `json:"createdAt,omitempty"`
	Href      string `json:"href,omitempty"`
	Id        string `json:"id,omitempty"`
	UpdatedAt int64  `json:"updatedAt,omitempty"`
}
