/*
 * Purport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomerNetwork struct {
	Address string `json:"address"`
	Name    string `json:"name,omitempty"`
}
