/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Ikev2Config struct {
	Esp *Ikev2EspConfig `json:"esp"`
	Ike *Ikev2IkeConfig `json:"ike"`
}
