/*
 * Pureport Control Plane
 *
 * Pureport API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CloudService struct {
	CloudRegion     *Link  `json:"cloudRegion,omitempty"`
	Href            string `json:"href,omitempty"`
	Id              string `json:"id,omitempty"`
	Ipv4PrefixCount int32  `json:"ipv4PrefixCount,omitempty"`
	Ipv6PrefixCount int32  `json:"ipv6PrefixCount,omitempty"`
	Name            string `json:"name"`
	Provider        string `json:"provider"`
	Service         string `json:"service"`
}
